# Generated by Django 3.2.5 on 2022-04-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
