# Generated by Django 3.2.5 on 2022-04-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_detail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50),
        ),
    ]
