# Generated by Django 3.2.5 on 2022-04-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220402_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
