# Generated by Django 3.2.5 on 2022-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='duration',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Acropolis Institue of Technology and Research, Indore', max_length=100),
        ),
    ]
