# Generated by Django 4.0.4 on 2022-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='acm_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
    ]
