# Generated by Django 4.0.4 on 2022-04-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_acm_designation_team_acmw_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='acmw_designation',
            field=models.CharField(blank=True, default='Member', max_length=50),
        ),
    ]
